import { getRepoDirectory, getRepoFile } from "@/lib/github";

export default async function SopsPage() {
  const files = await getRepoDirectory("sops");
  const first = files.find((file) => file.type === "file");
  const firstContents = first ? await getRepoFile(first.path) : null;

  return (
    <div className="space-y-4">
      <header>
        <h2 className="text-2xl text-[#0d2b1a]" style={{ fontFamily: "var(--font-dm-serif)" }}>
          SOP library
        </h2>
        <p className="text-sm text-[#6b7280]">Read-only SOPs generated by Hermes.</p>
      </header>

      {files.length === 0 ? (
        <div className="rounded-xl border border-dashed border-[#d1d5db] bg-white p-6 text-sm text-[#4b5563]">
          No SOP files found. Ask Hermes in Telegram to generate one.
        </div>
      ) : (
        <div className="grid gap-4 lg:grid-cols-[320px_1fr]">
          <aside className="rounded-xl border border-[#d1d5db] bg-white p-4">
            <h3 className="mb-2 text-sm font-medium text-[#111827]">Files</h3>
            <ul className="space-y-1 text-sm text-[#374151]">
              {files
                .filter((file) => file.type === "file")
                .map((file) => (
                  <li key={file.path}>{file.name}</li>
                ))}
            </ul>
          </aside>
          <article className="rounded-xl border border-[#d1d5db] bg-white p-4">
            <h3 className="mb-2 text-sm font-medium text-[#111827]">{first?.name ?? "Preview"}</h3>
            <pre className="overflow-auto whitespace-pre-wrap text-xs text-[#374151]">
              {firstContents ?? "Select a file to preview its content."}
            </pre>
          </article>
        </div>
      )}
    </div>
  );
}
