import Link from "next/link";
import { getRepoDirectory, getRepoFile, getRepoLastSync } from "@/lib/github";

type SopsPageProps = {
  searchParams: Promise<{
    file?: string;
  }>;
};

export default async function SopsPage({ searchParams }: SopsPageProps) {
  const params = await searchParams;
  const [files, lastSync] = await Promise.all([getRepoDirectory("sops"), getRepoLastSync()]);
  const list = files.filter((file) => file.type === "file");
  const selected = list.find((file) => file.path === params.file) ?? list[0];
  const selectedContents = selected ? await getRepoFile(selected.path) : null;

  return (
    <div className="space-y-4">
      <header>
        <h2 className="text-2xl text-[#0d2b1a]" style={{ fontFamily: "var(--font-dm-serif)" }}>
          SOP library
        </h2>
        <p className="text-sm text-[#6b7280]">Read-only SOPs generated by Hermes.</p>
        <p className="text-xs text-[#9ca3af]">
          Last synced: {lastSync ? new Date(lastSync).toLocaleString() : "Unknown"}
        </p>
      </header>

      {list.length === 0 ? (
        <div className="rounded-xl border border-dashed border-[#d1d5db] bg-white p-6 text-sm text-[#4b5563]">
          No SOP files found. Ask Hermes in Telegram to generate one.
        </div>
      ) : (
        <div className="grid gap-4 lg:grid-cols-[320px_1fr]">
          <aside className="rounded-xl border border-[#d1d5db] bg-white p-4">
            <h3 className="mb-2 text-sm font-medium text-[#111827]">Files</h3>
            <ul className="space-y-1 text-sm text-[#374151]">
              {list.map((file) => (
                <li key={file.path}>
                  <Link
                    href={`/dashboard/sops?file=${encodeURIComponent(file.path)}`}
                    className={
                      selected?.path === file.path ? "font-medium text-[#0d2b1a] underline" : "text-[#374151]"
                    }
                  >
                    {file.name}
                  </Link>
                </li>
              ))}
            </ul>
          </aside>
          <article className="rounded-xl border border-[#d1d5db] bg-white p-4">
            <h3 className="mb-2 text-sm font-medium text-[#111827]">{selected?.name ?? "Preview"}</h3>
            <pre className="overflow-auto whitespace-pre-wrap text-xs text-[#374151]">
              {selectedContents ?? "Select a file to preview its content."}
            </pre>
          </article>
        </div>
      )}
    </div>
  );
}
